// <auto-generated />
namespace PrsEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedPurchaseRequestLineItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPurchaseRequestLineItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201806121408011_added Purchase Request Line Item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
